<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مشتریان بانک
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    وقتی اسم مشتریان بانک را می‌شنویم، شاید اولین گزینه‌ای که به ذهنمان می‌رسد همان افرادی هستند که پشت باجه‌ها صف‌های طولانی تشکیل می‌دهند؛ پس طبیعتا اگر بخواهیم با استفاده یادگیری ماشین کمکی به آن‌ها بکنیم، اولین ایده این است که پیشبینی کنیم در چه زمانی به بانک مراجعه کنند که زمان کمتری در صف منتظر بمانند!
    <br>
     اما در این تمرین از طرف بانک مامور شده‌ایم تا با تحلیل پویش‌های بازاریابی (Marketing Campaign) بانک، تخمین بزنیم در پویش‌های پیشِ رو، چه افرادی ممکن است به پویش پاسخ مثبت بدهند.
    <br>
    با سرمایه‌گذاری روی افرادی که احتمال سپرده‌گذاری آن‌ها بیشتر است، بانک می‌توان پول بیشتری را در گاوصندوق‌های خود ذخیره کند و از این طریق رتبه خود را افزایش دهد و بتواند خدمات بیشتری برای مشتریان خود ارائه کند.
    <br>
   در این تمرین اطلاعات کمپین (پویش)‌های پیشین یک بانک پرتغالی را در اختیار داریم و قصد داریم افرادی را شناسایی کنیم که به پویش فعلی پاسخ مثبت می‌هند. هدف این پویش، ایجاد «سپرده مدت دار بانکی» است.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    با مجموعه داده این تمرین، در تمرین «بازاریابی بانکی» از فصل مهندسی ویژگی آشنا شده‌ایم.
    <br>
در این تمرین، مانند تمرین‌های پیشین دو مجموعه‌داده در اختیار شما قرار می‌گیرد که یکی مربوط به مجموعه آموزش و دیگری مجموعه آزمون است. 
    <br>
    در مجموعه آموزش، ۳۹۱۸۸ سطر و ۲۱ ستون وجود دارد که در جدول زیر، توضیحات ستون‌ها را با هم مرور می‌کنیم.
    <br>
    طبیعی است که مجموعه آزمون، ستون متغیرهدف را نداشته باشد و با مجموعا ۲۰ ستون در اختیار شما قرار بگیرد!
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|age|ستونی دارای مقادیر عددی که سن مشتری را نشان می‌دهد|
|job|ستونی با مقادیر دسته‌ای که وضعیت شغلی مشتری را نشان می‌دهد|
|marital|این ستون که مقادیر دسته‌ای را می‌پذیرد، وضعیت تاهل مشتری را مدل کرده است|
|education|وضعیت تحصیلی مشتری را به شکل دسته‌ای، نشان می‌دهد|
|default|نشان می‌دهد که آیا به صورت پیشفرض، مشتری اعتبار بانکی دارد یا خیر|
|housing|آیا مشتری برای مسکن، وتم گرفته است یا خیر|
|loan|آیا مشتری وام شخصی دریافت کرده است یا خیر؟|
|contact|نحوه ارتباط با مشتری را نشان می‌دهد. این ستون یکی از دو مقدار *cellular* و *telephone* را می‌تواند اختیار کند. به این معنی که بانک با تلفن همراه مشتری تماس گرفته است یا تلفن ثابت|
|month|این ستون دسته‌ای، نشان می‌دهد آخرین باری که با مشتری تماس گرفته شده است، در چه ماهی بوده است|
|day_of_week|روزی که آخرین تماس با مشتری گرفته شده است، چه روزی بوده است؟ (شنبه، یکشنبه، ...، جمعه)|
|campaign|تعداد تماس‌هایی که تا به حال با مشتری برای کمپین جاری گرفته شده است|
|pdays|تعداد روزی که از آخرین تماس با مشتری برای کمپین قبلی می‌گذرد. عدد ۹۹۹ به این معنی است که قبلا با مشتری تماس گرفته نشده است|
|previous|تعداد تماس‌هایی که با مشتری برای کمپین‌های قبلی گرفته شده است|
|poutcome|نتیجه کمپین‌های قبلی برای مشتری|
|emp.var.rate|نرخ تغییرات اشتغال در بازه سه ماهه|
|cons.price.idx|شاخص قیمت مصرف‌کننده در بازه یک ماهه|
|cons.conf.idx|شاخص اعتماد مصرف‌کننده در بازه یک ماهه|
|euribor3m|نرخ بهره بانکی برای وام‌های بین بانکی اروپایی|
|nr.employed|تعداد کارمندان در بازه سه ماهه|
|y|آیا فرد به پویش سرمایه‌گذاری بانک پاسخ مثبت داده یا خیر|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    مجموعه داده آزمایش، دقیقا مانند مجموعه داده آموزش است با این تفاوت که ستون <code>y</code> را ندارد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>bank_customers_train.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>bank_customers_test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از دادگان آموزشی را به عنوان دادگان اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [2]:
train_data = pd.read_csv('../data/bank_customers_train.csv')
test_data = pd.read_csv('../data/bank_customers_test.csv')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [3]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39188 entries, 0 to 39187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             39188 non-null  int64
 1   job             38872 non-null  object
 2   marital         39109 non-null  object
 3   education       37535 non-null  object
 4   default         31026 non-null  object
 5   housing         38248 non-null  object
 6   loan            38248 non-null  object
 7   contact         39188 non-null  object
 8   month           39188 non-null  object
 9   day_of_week     39188 non-null  object
 10  duration        39188 non-null  int64
 11  campaign        39188 non-null  int64
 12  pdays           39188 non-null  int64
 13  previous        39188 non-null  int64
 14  poutcome        39188 non-null  object
 15  emp.var.rate    39188 non-null  float64
 16  cons.price.idx  39188 non-null  float64
 17  cons.conf.idx   39188 non-null  float64
 18  euribor3m       39188 non-null  float64
 19  nr.employed     39188 non-null  float64
 20  y               39188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.3+ MB

In [4]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             2000 non-null   int64
 1   job             1986 non-null   object
 2   marital         1999 non-null   object
 3   education       1922 non-null   object
 4   default         1565 non-null   object
 5   housing         1950 non-null   object
 6   loan            1950 non-null   object
 7   contact         2000 non-null   object
 8   month           2000 non-null   object
 9   day_of_week     2000 non-null   object
 10  duration        2000 non-null   int64
 11  campaign        2000 non-null   int64
 12  pdays           2000 non-null   int64
 13  previous        2000 non-null   int64
 14  poutcome        2000 non-null   object
 15  emp.var.rate    2000 non-null   float64
 16  cons.price.idx  2000 non-null   float64
 17  cons.conf.idx   2000 non-null   float64
 18  euribor3m       2000 non-null   float64
 19  nr.employed     2000 non-null   float64
dtypes: float64(5), int64(5), object(10)
memory usage: 312.6+ KB

In [5]:
train_data.isnull().sum()

age                  0
job                316
marital             79
education         1653
default           8162
housing            940
loan               940
contact              0
month                0
day_of_week          0
duration             0
campaign             0
pdays                0
previous             0
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
y                    0
dtype: int64

In [6]:
numeric_columns = train_data.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [7]:
for column in numeric_columns:
    Q1 = train_data[column].quantile(0.25)
    Q3 = train_data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    train_data[column] = train_data[column].where((train_data[column] >= lower_bound) & (train_data[column] <= upper_bound))

In [8]:
train_data.isnull().sum()

age                439
job                316
marital             79
education         1653
default           8162
housing            940
loan               940
contact              0
month                0
day_of_week          0
duration          2795
campaign          2291
pdays             1437
previous          5357
poutcome             0
emp.var.rate         0
cons.price.idx       0
cons.conf.idx      428
euribor3m            0
nr.employed          0
y                    0
dtype: int64

In [9]:
for column in numeric_columns:
    Q1 = test_data[column].quantile(0.25)
    Q3 = test_data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    test_data[column] = test_data[column].where((test_data[column] >= lower_bound) & (test_data[column] <= upper_bound))

In [10]:
columns = [column for column in list(train_data.columns) if train_data[column].dtype == 'object']
columns

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'poutcome',
 'y']

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'most_frequent')
train_data[columns] = imputer.fit_transform(train_data[columns])

In [12]:
columns.remove('y')
columns

['job',
 'marital',
 'education',
 'default',
 'housing',
 'loan',
 'contact',
 'month',
 'day_of_week',
 'poutcome']

In [13]:
imputer = SimpleImputer(strategy = 'most_frequent')
test_data[columns] = imputer.fit_transform(test_data[columns])

In [14]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39188 entries, 0 to 39187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             38749 non-null  float64
 1   job             39188 non-null  object
 2   marital         39188 non-null  object
 3   education       39188 non-null  object
 4   default         39188 non-null  object
 5   housing         39188 non-null  object
 6   loan            39188 non-null  object
 7   contact         39188 non-null  object
 8   month           39188 non-null  object
 9   day_of_week     39188 non-null  object
 10  duration        36393 non-null  float64
 11  campaign        36897 non-null  float64
 12  pdays           37751 non-null  float64
 13  previous        33831 non-null  float64
 14  poutcome        39188 non-null  object
 15  emp.var.rate    39188 non-null  float64
 16  cons.price.idx  39188 non-null  float64
 17  cons.conf.idx   38760 non-null  float64
 18  euribor3m       39188 non-null  float64
 19  nr.employed     39188 non-null  float64
 20  y               39188 non-null  object
dtypes: float64(10), object(11)
memory usage: 6.3+ MB

In [15]:
numeric_columns = train_data.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [16]:
imputer = SimpleImputer(strategy = 'mean')
train_data[numeric_columns] = imputer.fit_transform(train_data[numeric_columns])

In [17]:
test_data[numeric_columns] = imputer.fit_transform(test_data[numeric_columns])

In [18]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39188 entries, 0 to 39187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             39188 non-null  float64
 1   job             39188 non-null  object
 2   marital         39188 non-null  object
 3   education       39188 non-null  object
 4   default         39188 non-null  object
 5   housing         39188 non-null  object
 6   loan            39188 non-null  object
 7   contact         39188 non-null  object
 8   month           39188 non-null  object
 9   day_of_week     39188 non-null  object
 10  duration        39188 non-null  float64
 11  campaign        39188 non-null  float64
 12  pdays           39188 non-null  float64
 13  previous        39188 non-null  float64
 14  poutcome        39188 non-null  object
 15  emp.var.rate    39188 non-null  float64
 16  cons.price.idx  39188 non-null  float64
 17  cons.conf.idx   39188 non-null  float64
 18  euribor3m       39188 non-null  float64
 19  nr.employed     39188 non-null  float64
 20  y               39188 non-null  object
dtypes: float64(10), object(11)
memory usage: 6.3+ MB

In [19]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             2000 non-null   float64
 1   job             2000 non-null   object
 2   marital         2000 non-null   object
 3   education       2000 non-null   object
 4   default         2000 non-null   object
 5   housing         2000 non-null   object
 6   loan            2000 non-null   object
 7   contact         2000 non-null   object
 8   month           2000 non-null   object
 9   day_of_week     2000 non-null   object
 10  duration        2000 non-null   float64
 11  campaign        2000 non-null   float64
 12  pdays           2000 non-null   float64
 13  previous        2000 non-null   float64
 14  poutcome        2000 non-null   object
 15  emp.var.rate    2000 non-null   float64
 16  cons.price.idx  2000 non-null   float64
 17  cons.conf.idx   2000 non-null   float64
 18  euribor3m       2000 non-null   float64
 19  nr.employed     2000 non-null   float64
dtypes: float64(10), object(10)
memory usage: 312.6+ KB

#OrdinalEncoder: 'month', 'day_of_week'

#OneHotEncoder: 'job', 'marital', 'education', 'poutcome'

#LabelEncoder: 'default', 'housing', 'loan', 'contact'

In [20]:
test_data['contact'].unique()

array(['cellular', 'telephone'], dtype=object)

In [21]:
from sklearn.preprocessing import OrdinalEncoder
ol = OrdinalEncoder(categories = [['jan', 'feb', 'mar', 'apr', 'may', 'jun', 
                                 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'],['mon', 'tue', 'wed', 'thu', 'fri']])
train_data[['month', 'day_of_week']] = ol.fit_transform(train_data[['month', 'day_of_week']]).astype(int)
test_data[['month', 'day_of_week']] = ol.transform(test_data[['month', 'day_of_week']]).astype(int)

In [22]:
train_data.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,35.0,blue-collar,single,high.school,no,no,no,cellular,6,3,...,3.0,999.0,0.0,nonexistent,1.4,93.918,-42.700000,4.958,5228.1,no
1,52.0,blue-collar,married,university.degree,no,yes,no,telephone,5,3,...,4.0,999.0,0.0,nonexistent,1.4,94.465,-41.800000,4.961,5228.1,no
2,38.0,services,married,high.school,no,no,no,telephone,5,1,...,2.0,999.0,0.0,nonexistent,1.4,94.465,-41.800000,4.864,5228.1,no
3,44.0,admin.,married,university.degree,no,yes,no,telephone,9,2,...,1.0,999.0,0.0,nonexistent,-3.4,92.431,-40.650036,0.735,5017.5,yes
4,25.0,services,divorced,basic.4y,no,yes,no,telephone,4,4,...,1.0,999.0,0.0,nonexistent,1.1,93.994,-36.400000,4.859,5191.0,no

In [23]:
y_train = train_data['y']

In [24]:
train_data.drop('y', axis = 1, inplace = True)

In [25]:
y_train

0         no
1         no
2         no
3        yes
4         no
        ...
39183     no
39184     no
39185    yes
39186     no
39187     no
Name: y, Length: 39188, dtype: object

In [26]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39188 entries, 0 to 39187
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             39188 non-null  float64
 1   job             39188 non-null  object
 2   marital         39188 non-null  object
 3   education       39188 non-null  object
 4   default         39188 non-null  object
 5   housing         39188 non-null  object
 6   loan            39188 non-null  object
 7   contact         39188 non-null  object
 8   month           39188 non-null  int32
 9   day_of_week     39188 non-null  int32
 10  duration        39188 non-null  float64
 11  campaign        39188 non-null  float64
 12  pdays           39188 non-null  float64
 13  previous        39188 non-null  float64
 14  poutcome        39188 non-null  object
 15  emp.var.rate    39188 non-null  float64
 16  cons.price.idx  39188 non-null  float64
 17  cons.conf.idx   39188 non-null  float64
 18  euribor3m       39188 non-null  float64
 19  nr.employed     39188 non-null  float64
dtypes: float64(10), int32(2), object(8)
memory usage: 5.7+ MB

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
columns_to_encode = ['default', 'housing', 'loan', 'contact']

label_encoder = LabelEncoder()

for column in columns_to_encode:
    train_data[column] = label_encoder.fit_transform(train_data[column])
    test_data[column] = label_encoder.transform(test_data[column])

In [29]:
train_data[columns]

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome
0,blue-collar,single,high.school,0,0,0,0,6,3,nonexistent
1,blue-collar,married,university.degree,0,1,0,1,5,3,nonexistent
2,services,married,high.school,0,0,0,1,5,1,nonexistent
3,admin.,married,university.degree,0,1,0,1,9,2,nonexistent
4,services,divorced,basic.4y,0,1,0,1,4,4,nonexistent
...,...,...,...,...,...,...,...,...,...,...
39183,admin.,single,university.degree,0,0,0,0,4,1,nonexistent
39184,admin.,married,high.school,0,0,0,0,3,4,nonexistent
39185,blue-collar,married,basic.4y,0,0,0,1,5,4,nonexistent
39186,admin.,single,university.degree,0,1,0,1,5,2,nonexistent
39187,blue-collar,married,basic.9y,0,1,0,1,5,1,nonexistent

In [30]:
columns = ['job', 'marital', 'education', 'poutcome']
dummy_train = pd.get_dummies(train_data[columns]).astype('int64')

In [31]:
dummy_train

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,poutcome_failure,poutcome_nonexistent,poutcome_success
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
4,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39183,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
39184,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
39185,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
39186,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
39187,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [32]:
train_data = pd.concat([train_data, dummy_train], axis = 1)
train_data.drop(train_data[columns], axis = 1, inplace = True)

In [33]:
train_data.head()

,age,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,...,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,poutcome_failure,poutcome_nonexistent,poutcome_success
0,35.0,0,0,0,0,6,3,117.000000,3.0,999.0,...,0,0,0,1,0,0,0,0,1,0
1,52.0,0,1,0,1,5,3,118.000000,4.0,999.0,...,0,0,0,0,0,0,1,0,1,0
2,38.0,0,0,0,1,5,1,253.000000,2.0,999.0,...,0,0,0,1,0,0,0,0,1,0
3,44.0,0,1,0,1,9,2,203.513203,1.0,999.0,...,0,0,0,0,0,0,1,0,1,0
4,25.0,0,1,0,1,4,4,601.000000,1.0,999.0,...,1,0,0,0,0,0,0,0,1,0

In [34]:
test_data.shape

(2000, 20)

In [35]:
dummy_test = pd.get_dummies(test_data[columns]).astype('int64')

In [36]:
test_data = pd.concat([test_data, dummy_test], axis = 1)
test_data.drop(test_data[columns], axis = 1, inplace = True)

In [37]:
test_data.shape

(2000, 40)

In [38]:
train_data.head()

,age,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,...,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,poutcome_failure,poutcome_nonexistent,poutcome_success
0,35.0,0,0,0,0,6,3,117.000000,3.0,999.0,...,0,0,0,1,0,0,0,0,1,0
1,52.0,0,1,0,1,5,3,118.000000,4.0,999.0,...,0,0,0,0,0,0,1,0,1,0
2,38.0,0,0,0,1,5,1,253.000000,2.0,999.0,...,0,0,0,1,0,0,0,0,1,0
3,44.0,0,1,0,1,9,2,203.513203,1.0,999.0,...,0,0,0,0,0,0,1,0,1,0
4,25.0,0,1,0,1,4,4,601.000000,1.0,999.0,...,1,0,0,0,0,0,0,0,1,0

In [39]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39188 entries, 0 to 39187
Data columns (total 40 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            39188 non-null  float64
 1   default                        39188 non-null  int32
 2   housing                        39188 non-null  int32
 3   loan                           39188 non-null  int32
 4   contact                        39188 non-null  int32
 5   month                          39188 non-null  int32
 6   day_of_week                    39188 non-null  int32
 7   duration                       39188 non-null  float64
 8   campaign                       39188 non-null  float64
 9   pdays                          39188 non-null  float64
 10  previous                       39188 non-null  float64
 11  emp.var.rate                   39188 non-null  float64
 12  cons.price.idx                 39188 non-null  float64
 13  cons.conf.idx                  39188 non-null  float64
 14  euribor3m                      39188 non-null  float64
 15  nr.employed                    39188 non-null  float64
 16  job_admin.                     39188 non-null  int64
 17  job_blue-collar                39188 non-null  int64
 18  job_entrepreneur               39188 non-null  int64
 19  job_housemaid                  39188 non-null  int64
 20  job_management                 39188 non-null  int64
 21  job_retired                    39188 non-null  int64
 22  job_self-employed              39188 non-null  int64
 23  job_services                   39188 non-null  int64
 24  job_student                    39188 non-null  int64
 25  job_technician                 39188 non-null  int64
 26  job_unemployed                 39188 non-null  int64
 27  marital_divorced               39188 non-null  int64
 28  marital_married                39188 non-null  int64
 29  marital_single                 39188 non-null  int64
 30  education_basic.4y             39188 non-null  int64
 31  education_basic.6y             39188 non-null  int64
 32  education_basic.9y             39188 non-null  int64
 33  education_high.school          39188 non-null  int64
 34  education_illiterate           39188 non-null  int64
 35  education_professional.course  39188 non-null  int64
 36  education_university.degree    39188 non-null  int64
 37  poutcome_failure               39188 non-null  int64
 38  poutcome_nonexistent           39188 non-null  int64
 39  poutcome_success               39188 non-null  int64
dtypes: float64(10), int32(6), int64(24)
memory usage: 11.1 MB

In [40]:
test_data.head()

,age,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,...,education_basic.4y,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,poutcome_failure,poutcome_nonexistent,poutcome_success
0,47.0,0,1,0,0,7,2,58.0,3.0,999.0,...,0,0,0,0,0,1,0,0,1,0
1,35.0,0,1,1,0,10,2,293.0,2.0,999.0,...,0,0,0,0,0,0,1,1,0,0
2,34.0,0,1,0,1,3,0,7.0,5.0,999.0,...,0,1,0,0,0,0,0,0,1,0
3,31.0,0,0,0,1,7,1,225.0,2.0,999.0,...,0,0,0,0,0,1,0,0,1,0
4,58.0,0,1,0,0,4,1,159.0,1.0,999.0,...,0,0,0,1,0,0,0,1,0,0

In [41]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 40 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            2000 non-null   float64
 1   default                        2000 non-null   int32
 2   housing                        2000 non-null   int32
 3   loan                           2000 non-null   int32
 4   contact                        2000 non-null   int32
 5   month                          2000 non-null   int32
 6   day_of_week                    2000 non-null   int32
 7   duration                       2000 non-null   float64
 8   campaign                       2000 non-null   float64
 9   pdays                          2000 non-null   float64
 10  previous                       2000 non-null   float64
 11  emp.var.rate                   2000 non-null   float64
 12  cons.price.idx                 2000 non-null   float64
 13  cons.conf.idx                  2000 non-null   float64
 14  euribor3m                      2000 non-null   float64
 15  nr.employed                    2000 non-null   float64
 16  job_admin.                     2000 non-null   int64
 17  job_blue-collar                2000 non-null   int64
 18  job_entrepreneur               2000 non-null   int64
 19  job_housemaid                  2000 non-null   int64
 20  job_management                 2000 non-null   int64
 21  job_retired                    2000 non-null   int64
 22  job_self-employed              2000 non-null   int64
 23  job_services                   2000 non-null   int64
 24  job_student                    2000 non-null   int64
 25  job_technician                 2000 non-null   int64
 26  job_unemployed                 2000 non-null   int64
 27  marital_divorced               2000 non-null   int64
 28  marital_married                2000 non-null   int64
 29  marital_single                 2000 non-null   int64
 30  education_basic.4y             2000 non-null   int64
 31  education_basic.6y             2000 non-null   int64
 32  education_basic.9y             2000 non-null   int64
 33  education_high.school          2000 non-null   int64
 34  education_illiterate           2000 non-null   int64
 35  education_professional.course  2000 non-null   int64
 36  education_university.degree    2000 non-null   int64
 37  poutcome_failure               2000 non-null   int64
 38  poutcome_nonexistent           2000 non-null   int64
 39  poutcome_success               2000 non-null   int64
dtypes: float64(10), int32(6), int64(24)
memory usage: 578.2 KB

In [42]:
y_train = pd.DataFrame(y_train, columns = ['y'])

In [43]:
y_train

         y
0       no
1       no
2       no
3      yes
4       no
...    ...
39183   no
39184   no
39185  yes
39186   no
39187   no

[39188 rows x 1 columns]

In [44]:
encoder = LabelEncoder()

In [45]:
y_train['y'] = encoder.fit_transform(y_train['y'])

In [46]:
y_train

       y
0      0
1      0
2      0
3      1
4      0
...   ..
39183  0
39184  0
39185  1
39186  0
39187  0

[39188 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدلسازی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    الگوریتم <i>رگرسیون لجستیک</i> با نام <code>AdaBoostClassifier</code> در پکیج <code>ensemble</code> این کتابخانه در دسترس است. برخی از آرگومان‌های مهم آن در جدول زیر آمده است، اما جهت مطالعه‌ی کامل‌تر مستندات می‌توانید به <a href="https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html" target="_blank">این لینک</a> مراجعه فرمایید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|آرگومان|جنس و تایپ|توضیحات|
|:------:|:--------:|:---:|
|base_estimator|<code>object</code> یا <code>None</code>|مدل تخمین‌زن پایه الگوریتم آدابوست را با این آرگومان مشخص می‌کنیم. در این آرگومان می‌توانیم مدلی مانند جنگل تصادفی قرار دهیم. اگر مقداری برای این آرگومان در نظر نگیریم، به طور پیشفرض،‌الگوریتم درخت تصمیم به عنوان تخمین‌زن پایه در نظر گرفته می‌شود.|
|n_estimators|<code>int</code>|تعداد تخمین‌زن‌های پایه که دوست داریم با هم دیگر ادغام شوند و الگوریتم آدابوست را تشکیل دهند، با این آرگومان مشخص می‌کنیم. این آرگومان به صورت پیشفرض روی عدد ۵۰ تنظیم شده است.|
|learning_rate|<code>float</code>|این آرگومان، وزن هر تخمین‌زن در هر چرخه بوستینگ را مشخص می‌کند. به عبارت بهتر آنچه این آرگومان مشخص می‌کند، تاثیر هر تخمین‌زن در خروجی مدل است. در این کتابخانه، همه تخمین‌زن‌های ساده به یک اندازه در خروجی مدل تاثیر می‌گذارند.|
|random_state|<code>int</code>|وضعیت تصادفی‌بودن تخمین‌زن‌های پایه در هر چرخه بوستینگ را با این آرگومان مشخص می‌کنیم. برای مطالعه بیشتر، می‌توانید <a href="https://scikit-learn.org/stable/glossary.html#term-random_state" target="_blank">این لینک</a> را مطالعه کنید.|


</font>
</div>
</center>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در سلول زیر با استفاده از مدل آماده‌ای که در بالا شرح داده شد و به کمک تابع <code>fit</code> الگوریتم را بر روی دادگان آموزشی اجرا کنید.
</font>
</p>

# Random Search

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_data,y_train, test_size=0.2, random_state=42)

In [48]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import AdaBoostClassifier

In [49]:
base_model = AdaBoostClassifier()
param_distributions = {
    'n_estimators' : np.arange(50, 201, 10),
    'learning_rate' : np.linspace(0.1, 2, 20)}

In [50]:
random_search = RandomizedSearchCV(
    estimator = base_model,
    param_distributions = param_distributions,
    scoring = 'f1',
    n_iter=50, 
    cv = 5,
    random_state = 42,
)

In [51]:
random_search.fit(X_train, y_train)

C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

RandomizedSearchCV(cv=5, estimator=AdaBoostClassifier(), n_iter=50,
                   param_distributions={'learning_rate': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ]),
                                        'n_estimators': array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200])},
                   random_state=42, scoring='f1')

In [52]:
print("Best Parameters:", random_search.best_params_)
print("Best Cross-Validation Score:", random_search.best_score_)

Best Parameters: {'n_estimators': 180, 'learning_rate': 1.8}
Best Cross-Validation Score: 0.50052361530625

In [54]:
best_model = random_search.best_estimator_

In [55]:
best_model.fit(X_train, y_train)

C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostClassifier(learning_rate=1.8, n_estimators=180)

In [64]:
model = best_model

# first way (resample)

In [48]:
y_train.value_counts()

y
0    34773
1     4415
Name: count, dtype: int64

In [49]:
from imblearn.over_sampling import SMOTE

In [50]:
smote = SMOTE(random_state = 42)

In [51]:
x_resample, y_resample = smote.fit_resample(train_data, y_train)

In [52]:
y_resample.value_counts()

y
0    34773
1    34773
Name: count, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_resample,y_resample, test_size=0.2, random_state=42)

In [54]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier( )
model.fit(X_train, y_train)

C:\Users\hahmadi\Desktop\Hossein John\Machine learning\qenv\lib\site-packages\sklearn\utils\validation.py:1141: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostClassifier()

# another way ( class_weight )

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_data,y_train, test_size=0.2, random_state=42)

In [66]:
from sklearn.utils.class_weight import compute_sample_weight

In [67]:
sample_weights = compute_sample_weight(class_weight = 'balanced', y = y_train)

In [75]:
from sklearn.ensemble import AdaBoostClassifier
#model = AdaBoostClassifier()
model.fit(X_train, y_train, class_weight='balanced')

TypeError: BaseWeightBoosting.fit() got an unexpected keyword argument 'class_weight'

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی دادگان آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

In [69]:
y_pred = model.predict(X_test)

In [70]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.6241935483870967

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>50 %</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|------|---|
|y|آیا شخص به پویش بازاریابی بانک پاسخ مثبت می‌دهد یا خیر|
    
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اسم دیتافریم باید <i>submission</i> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل ۱ ستون با اسم <i>y</i> است و ۲۰۰۰ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، اعداد ستون <i>y</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||y|
|----|-----|
|0|1|
|1|1|
|2|0|
|3|1|
|4|0|

</font>
</div>

In [71]:
y_pred_test = model.predict(test_data)

In [72]:
# predict test samples
submission = pd.DataFrame()
submission['y'] = y_pred_test

In [73]:
submission

      y
0     0
1     0
2     0
3     0
4     0
...  ..
1995  0
1996  0
1997  0
1998  1
1999  0

[2000 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [74]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

joblib.dump(model, 'model')
submission.to_csv('submission.csv', index=False)
file_names = ['bank_customers.ipynb', 'submission.csv', 'model']
compress(file_names)

File Paths:
['bank_customers.ipynb', 'submission.csv', 'model']